#!/usr/bin/env python

import sys
import monocleaner.monocleaner_train as train

def main(argv):
    args = train.initialization()
    train.perform_training(args)

if __name__ == '__main__':
    main(sys.argv[1:])
