#!/usr/bin/env python
import logging
import sys
import traceback
import monocleaner.util as util
import monocleaner.monocleaner_train as train

def main(argv):
    try:
        util.logging_setup()
        args = train.initialization() # Parsing parameters
        train.perform_training(args)  # Running main program
    except Exception as ex:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__ == '__main__':
    main(sys.argv[1:])
