#!/usr/bin/env python

import sys
import traceback
import logging
import monocleaner.util as util
import monocleaner.monocleaner_score as scorer

def main(argv):
    try:
        util.logging_setup()
        args = scorer.initialization() # Parsing parameters
        scorer.main(args)  # Running main program
    except Exception as ex:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__=="__main__":
    main(sys.argv[1:])
